[
  ['alt.binaries.dvdr', 'This group contains DVD Movies.'],
  ['alt.binaries.boneless', 'This group contains XVID and X264 Movies. Some Foreign.'],
  ['alt.binaries.multimedia', 'This group contains TV, Movies, and Music.'],
  ['alt.binaries.movies.divx', 'This group contains XVID Movies'],
  ['alt.binaries.games.xbox', 'This group contains original XBOX Games.'],
  ['alt.binaries.movies.xvid', 'This group contains XVID Movies.'],
  ['alt.binaries.sony.psp', 'This group contains PSP Games.'],
  ['alt.binaries.nintendo.ds', 'This group contains Nintendo DS Games'],
  ['alt.binaries.games.nintendods', 'This group contains Nintendo DS Games '],
  ['alt.binaries.hdtv.x264', 'This group contains X264 Movies and HDTV.'],
  ['alt.binaries.games.xbox360', 'This group contains XBOX 360 Games and DLC.'],
  ['alt.binaries.games.wii', 'This group contains Nintendo WII Games, WII-Ware, and VC.'],
  ['alt.binaries.wmvhd', 'This group contains WMVHD Movies.'],
  ['alt.binaries.x264', 'This group contains X264 Movies and TV.'],
  ['alt.binaries.wii', 'This group contains Nintendo WII Games, WII-Ware, and VC.'],
  ['alt.binaries.moovee', 'This group contains XVID and X264 Movies.'],
  ['alt.binaries.inner-sanctum', 'This group contains PC and Music.'],
  ['alt.binaries.warez.smartphone', 'This group contains Mobile Phone Apps.'],
  ['alt.binaries.teevee', 'This group contains X264 and XVID TV.'],
  ['alt.binaries.warez', 'This group contains PC 0DAY, PC ISO, and PC PHONE.'],
  ['alt.binaries.sounds.mp3.complete_cd', 'This group contains a variety of Music.'],
  ['alt.binaries.mpeg.video.music', 'This group contains a variety of Music Videos.'],
  ['alt.binaries.mp3', 'This group contains a variety of Music.'],
  ['alt.binaries.mma', 'This group contains MMA/TNA Sport TV.'],
  ['alt.binaries.sounds.mp3.classical', 'This group contains Classical Music.'],
  ['alt.binaries.mac', 'This group contains MAC/OSX Software.'],
  ['alt.binaries.e-book', 'This group contains E-Books.'],
  ['alt.binaries.warez.ibm-pc.0-day', 'This group contains PC-0Day.'],
  ['alt.binaries.tvseries', 'This group contains X264 and XVID TV.'],
  ['alt.binaries.ath', 'This group contains a variety of Music. Some Foreign.'],
  ['alt.binaries.ftn', 'This group contains a variety of Music and TV.'],
  ['alt.binaries.erotica', 'This group contains XXX.'],
  ['alt.binaries.games', 'This group contains PC and Console Games.'],
  ['alt.binaries.cores', 'This group contains a variety including Nintendo DS. Lots of Foreign.'],
  ['alt.binaries.country.mp3', 'This group contains Country Music.'],
  ['alt.binaries.sounds.mp3.1990s', 'This group contains Music from the 1990\'s.'],
  ['alt.binaries.console.ps3', 'This group contains PS3 Games.'],
  ['alt.binaries.scary.exe.files', 'This group contains XVID and X264 Movies.'],
  ['alt.binaries.cd.image', 'This group contains PC-ISO.'],
  ['alt.binaries.e-book.technical', 'This group contains E-Books.'],
  ['alt.binaries.erotica.divx', 'This group contains XXX.'],
  ['alt.binaries.test', 'This group contains a variety of content.'],
  ['alt.binaries.x', 'This group contains a variety of content. Some Foreign.'],
  ['alt.binaries.hou', 'This group contains a variety of content. Mostly Foreign.'],
  ['alt.binaries.pro-wrestling', 'This group contains WWE Sport TV.'],
  ['alt.binaries.sounds.lossless', 'This group contains a variety of Lossless Music.'],
  ['alt.binaries.comp', 'This group contains Warez. Mostly Foreign.'],
  ['alt.binaries.warez.quebec-hackers', 'This group contains PC-0day. Some Foreign.'],
  ['alt.binaries.sounds.mp3.bluegrass', 'This group contains Bluegrass Music.'],
  ['alt.binaries.sounds.radio.bbc', 'This group contains BBC Radio Music'],
  ['alt.binaries.e-book.flood', 'This group contains E-Books.'],
  ['alt.binaries.movies.erotica', 'This group contains XXX'],
  ['alt.binaries.multimedia.documentaries', 'This group contains Documentary Movies and TV.'],
  ['alt.binaries.sounds.mp3.jazz', 'This group contains Jazz Music.'],
  ['alt.binaries.multimedia.erotica.amateur', 'This group contains XXX.'],
  ['alt.binaries.sounds.1960s.mp3', 'This group contains Music from the 1960\'s.'],
  ['alt.binaries.sounds.1970s.mp3', 'This group contains Music from the 1970\'s.'],
  ['alt.binaries.sounds.mp3.comedy', 'This group contains Comedy Audio.'],
  ['alt.binaries.sounds.mp3.2000s', 'This group contains Music from the 2000\'s.'],
  ['alt.binaries.sounds.mp3.christian', 'This group contains Christian Music.'],
  ['alt.binaries.sounds.mp3.1950s', 'This group contains Music from the 1950\'s.'],
  ['alt.binaries.sounds.mp3.1970s', 'This group contains Music from the 1970\'s.'],
  ['alt.binaries.sounds.mp3.1980s', 'This group contains Music from the 1980\'s.'],
  ['alt.binaries.mp3.bootlegs', 'This group contains Bootleg Music.'],
  ['alt.binaries.sounds.mp3', 'This group contains a variety of Music.'],
  ['alt.binaries.mp3.audiobooks', 'This group contains Audio Books.'],
  ['alt.binaries.sounds.mp3.rap-hiphop.full-albums', 'This group contains Rap and Hip-Hop Music.'],
  ['alt.binaries.sounds.mp3.full_albums', 'This group contains a variety of Music.'],
  ['alt.binaries.multimedia.teen-idols', 'This group contains Music from Teen Idols'],
  ['alt.binaries.sounds.mp3.dance', 'This group contains Dance Music.'],
  ['alt.binaries.warez.uk.mp3', 'This group contains a variety of Music.'],
  ['alt.binaries.sounds.mp3.heavy-metal', 'This group contains Heavy Metal Music.'],
  ['alt.binaries.multimedia.cartoons', 'This group contains Cartoon TV and Movies.'],
  ['alt.binaries.multimedia.sports', 'This group contains Sports TV and Movies.'],
  ['alt.binaries.multimedia.anime', 'This group contains Anime TV and Movies.'],
  ['alt.binaries.sounds.lossless.classical', 'This group contains lossless Classical Music.'],
  ['alt.binaries.multimedia.disney', 'This group contains Disney TV and Movies.'],
  ['alt.binaries.sounds.mp3.nospam', 'This group contains a variety of Music.'],
  ['alt.binaries.multimedia.sitcoms', 'This group contains Sitcom TV.'],
  ['alt.binaries.sounds.radio.british', 'This group contains British Radio Music.'],
  ['alt.binaries.multimedia.comedy.british', 'This group contains British Comedy TV and Movies.'],
  ['alt.binaries.etc', 'This group contains a variety of items.'],
  ['alt.binaries.misc', 'This group contains a variety of items.'],
  ['alt.binaries.sounds.mp3.rock', 'This group contains Rock Music.'],
  ['alt.binaries.dc', 'This group contains XVID and X264 Movies and TV. Mostly Foreign.'],
  ['alt.binaries.documentaries', 'This group contains Documentaries TV and Movies.'],
  ['alt.binaries.cd.lossless', 'This group contains a variety of lossless Music.'],
  ['alt.binaries.sounds.audiobooks.repost', 'This group contains Audiobooks.'],
  ['alt.binaries.highspeed', 'This group contains XVID Movies. Mostly Foreign.'],
  ['alt.binaries.bloaf', 'This group contains a variety. Mostly Foreign.'],
  ['alt.binaries.big', 'This group contains XVID Movies. Mostly Foreign.'],
  ['alt.binaries.sounds.mp3.musicals', 'This group contains Musicals Music.'],
  ['alt.binaries.sound.mp3', 'This group contains a variety of Music.'],
  ['alt.binaries.sounds.mp3.jazz.vocals', 'This group contains Jazz Vocal Music.'],
  ['alt.binaries.dvd.movies', 'This group contains DVDR Movies.'],
  ['alt.binaries.ebook', 'This group contains Ebook\'s.'],
  ['alt.binaries.sounds.mp3.disco', 'This group contains Disco Music.'],
  ['alt.binaries.mp3.full_albums', 'This group contains a variety of Music.'],
  ['alt.binaries.tv', 'This group contains XVID TV.'],
  ['alt.binaries.sounds.lossless.country', 'This group contains lossless Country Music.'],
  ['alt.binaries.uzenet', 'This group contains XXX. Some Foreign.'],
  ['alt.binaries.mom', 'This group contains a variety. Mostly Foreign.'],
  ['alt.binaries.ijsklontje', 'This group contains XXX.'],
  ['alt.binaries.sounds.lossless.1960s', 'This group contains lossless 1960\'s Music.'],
  ['alt.binaries.sounds.mp3.emo', 'This group contains Emo Music.'],
  ['alt.binaries.classic.tv.shows', 'This group contains Classic TV and Movies.'],
  ['alt.binaries.dgma', 'This group contains XVID Movies. Mostly Foreign.'],
  ['alt.binaries.sounds.mp3.opera', 'This group contains Opera Music.'],
  ['alt.binaries.ipod.videos', 'This group contains Mobile TV and Movies.'],
  ['alt.binaries.music.opera', 'This group contains Opera Music.'],
  ['alt.binaries.sounds.flac.jazz', 'This group contains lossless Jazz Music.'],
  ['alt.binaries.multimedia.tv', 'This group contains XVID and X264 TV.'],
  ['alt.binaries.sounds.whitburn.pop', 'This group contains Pop Music.'],
  ['alt.binaries.sound.audiobooks', 'This group contains Audiobooks.'],
  ['alt.binaries.sounds.mp3.acoustic', 'This group contains Accoustic Music.'],
  ['alt.binaries.u-4all', 'This group contains XVID TV and Movies. Mostly Foreign.'],
  ['alt.binaries.sounds.mp3.progressive-country', 'This group contains Country Music.'],
  ['alt.binaries.multimedia.classic-films', 'This group contains Classic TV and Movies.'],
  ['alt.binaries.music.flac', 'This group contains a variety of lossless Music'],
  ['alt.binaries.ghosts', 'This group contains XVID TV and Movies. Mostly Foreign.'],
  ['alt.binaries.town', 'This group contains XVID TV and Movies. Mostly Foreign.'],
].each do |name,desc|
  Nizbel::Group.create(:name => name, :description => desc, :active => true)
end